Aanpassing inbeslagname
Tedeapolis/wet-en-regelgeving pull request #102
Opened 2021-03-12 13:15 UTC by TDA-SanderD

- Aanpassing gedaan aan het artikel omtrent inbeslagname zodat er overal "strafbaar feit" staat in plaats van op bepaalde plekken misdrijf en op andere plekken strafbaar feit. 
- Algemene aanvulling gedaan. De definitie van een strafbaar feit is in het wetboek gezet.

2021-03-12 17:08 UTC, marvinh85 commented
- Lijkt me niet helemaal juist in lid 2. Nu kan een auto dus ook in beslag genomen worden voor verkeerd parkeren of door rood rijden, gezien dit ook een strafbaar feit betreft? Hier stond specifiek misdrijf, om uit te sluiten dat voor alles een auto in beslag genomen kan worden. Dit lijkt me niet juist om lid 2 te veranderen naar strafbaar feit?

- Omtrent de laatste regel dat je het voertuig niet terug krijgt bij de 4de inbeslagname (na de 3rde keer) staat nu dat hij wordt vernietigd, maar dit is niet juist. Hij wordt verkocht op de veiling dan.

2021-03-13 21:32 UTC, TDA-SanderD commented
Rijden door rood is geen strafbaar feit. Het is een muldergedraging en dat is dus geen strafbaar feit. Daarom hoeft er ook niet per definitie een cautie worden voorgelezen bij het vragen van een verklaring voor een boete voor het rijden door rood en dergelijke. Soortgelijk aan de casus met de douanewet die aan je werd voorgelegd. De persoon die wordt staandegehouden is ook geen **verdachte** van een strafbaar feit maar een **betrokkene**. 

Enkele strafbare feiten uit de wegenverkeerswet:
- Artikel 5 WVW (een overtreding)
- Overschrijden van de maximumsnelheid met meer dan 100% 
- Artikel 5a WVW (een misdrijf)
- negeren stopteken

Dat zijn allemaal redenen waarop een voertuig momenteel in beslag wordt genomen door de politie. Ik heb ook specifiek gedefinieerd wat een strafbaar feit inhoudt om verwarring te voorkomen. 

Betreffende je tweede punt, dit zal ik aanpassen.

2021-03-13 21:43 UTC, TDA-SanderD commented
Ik begrijp echter wel enigszins wat je bedoelt aangezien onder andere fout parkeren wel in het wetboek van TDA staat onder verkeersdelicten. Wellicht een idee om te specificeren bij welke **verkeers**delicten er overgegaan mag worden tot inbeslagname?

2021-03-28 19:12 UTC, Willem-Dekker commented
Wat moet ik hier nu mee doen?

2021-04-09 14:40 UTC, TDA-SanderD commented
Aanpassing gedaan, ik ga nu even overleggen.

2021-04-10 21:35 UTC, TDA-SanderD commented
Deze kan doorgevoerd worden.

2021-04-11 19:52 UTC, Willem-Dekker requested changes
Zie comments

2021-04-11 19:52 UTC, Willem-Dekker commented on docs/wetboek.md
> +    * Plegen van een strafbaar feit uit het wetboek van TeDeApolis waarbij het goed direct of indirect betrokken is, behalve fout parkeren en een snelheidsovertreding;
Tedeapolis geen TeDeApolis

2021-04-11 20:34 UTC, TDA-SanderD commented on docs/wetboek.md
> +    * Plegen van een strafbaar feit uit het wetboek van TeDeApolis waarbij het goed direct of indirect betrokken is, behalve fout parkeren en een snelheidsovertreding;
Aangepast

2021-04-14 16:36 UTC, Willem-Dekker approved these changes

2021-04-14 16:36 UTC, merged