Aanpassing Artikel 7 omtrent baiting
Tedeapolis/wet-en-regelgeving pull request #117
Opened 2021-04-18 19:51 UTC by DevvTDA

Voorbeelden voor lid 2: Na een schietpartij achtervolgt worden door burgers zonder wapens. Nepmeldingen maken omtrent criminele activiteiten

2021-04-21 18:27 UTC, dilyano approved these changes

2021-04-25 18:11 UTC, Willem-Dekker requested changes

2021-04-25 18:11 UTC, Willem-Dekker commented on docs/apv.md
> +2. Hij/zij die moedwillig officieel gang members uitlokt met de intentie deze te irriteren en/of bezig te houden zal bestraft worden met een straf volgens de 1e categorie.
veranderen naar: het onnodig uitlokken zonder verdere intentie tot rp

2021-04-25 18:29 UTC, Willem-Dekker approved these changes

2021-04-25 18:30 UTC, merged