Aanpassingen aan artikel A4 - Strafbepaling
Tedeapolis/wet-en-regelgeving pull request #133
Opened 2021-05-21 17:29 UTC by TDA-SanderD

- Er is een aanpassing gedaan aan het wetboek, waardoor de regel "boven de 400 maanden geldt er een extra boete van 500 euro per maand" ook schriftelijk genoteerd staat.
- Er is verduidelijkt wat er moet gebeuren als iemand meerdere, dezelfde strafbare feiten pleegt en dit bestraft wordt tijdens één veroordeling. Hiermee wordt het volgende bedoeld: Iemand pleegt een winkeloverval en wordt niet gepakt. Er is duidelijk bewijs en er wordt een signalering opgemaakt. De verdachte pleegt enkele dagen later wederom een winkeloverval en hetzelfde geldt. Een week erna pleegt de verdachte nog een winkeloverval en hij wordt aangehouden. Hij heeft dus in totaal 3 winkelovervallen gepleegd, 2 signaleringen en 1 daadwerkelijk heterdaad.

2021-05-21 17:30 UTC, TDA-SanderD commented
Dit is besproken tijdens het overleg van politie- en justitieleiding, dus Nick en de rest zijn hiervan op de hoogte.

2021-05-24 15:25 UTC, Willem-Dekker requested changes
Kijk ff naar het commentaar, zitten wat linting dingen in

2021-05-24 15:25 UTC, Willem-Dekker commented on docs/wetboek.md
> +6.  Indien er sprake is van meermaals gepleegde exact dezelfde strafbare feiten waarbij er sprake is van andere omstandigheden, dan wordt er voor elk extra delict 50% van de oorspronkelijke straf van
ff kijken hier naar de linting, er zit hier bijvoorbeeld een spatie te veel voor

2021-05-24 16:45 UTC, TDA-SanderD commented
Ik heb het aangepast!

2021-06-01 17:05 UTC, Willem-Dekker approved these changes

2021-06-01 17:05 UTC, merged