Algemene aanpassing gevangenisstraffen
Tedeapolis/wet-en-regelgeving pull request #143
Opened 2021-06-14 12:02 UTC by TDA-SanderD

- Nagenoeg alle artikelen waarbij er een gevangenisstraf geldt zijn aangepast. De gevangenisstraf van deze artikelen is verlaagd met 10%. 
Enkele kleine wijzigingen:
- De boete voor belediging (van een ambtenaar in functie) is verhoogd.
- Vanaf heden krijg je een taakstraf in plaats van een gevangenisstraf als je de eerste keer betrapt wordt op het in bezit hebben van illegale diersoorten.

2021-06-15 10:30 UTC, Willem-Dekker requested changes

2021-06-15 10:30 UTC, Willem-Dekker commented on docs/wetboek.md
> +1. Schuldig is een persoon die opzettelijk een ander belegdigt op straffe van een boete van €1200,- per geval.
kosten pagina updaten

2021-06-16 09:27 UTC, TDA-SanderD commented on docs/wetboek.md
> +1. Schuldig is een persoon die opzettelijk een ander belegdigt op straffe van een boete van €1200,- per geval.
Aangepast!

2021-06-20 18:02 UTC, Willem-Dekker approved these changes

2021-06-20 18:03 UTC, merged