Update apv.md
Tedeapolis/wet-en-regelgeving pull request #154
Opened 2021-07-10 20:01 UTC by dilyano

2021-07-11 12:38 UTC, Willem-Dekker commented on docs/apv.md
> +1. Het campen van een niet actieve pluk op Narcopolis is niet toegestaan. Onder campen wordt verstaan het langer dan 5 minuten aanwezig zijn van een persoon of voertuig op een "pluk" locatie.
ik zou er een drugs locatie van maken ipv pluk

2021-07-12 09:11 UTC, Willem-Dekker requested changes
zelfde als vorige commentaar

2021-07-12 09:13 UTC, Willem-Dekker commented
ik lees ook in notulen dat tijd aangepast moet worden

2021-07-12 09:36 UTC, dilyano commented
@Willem-Dekker is al aangepast in die vorige commit ;)

2021-07-12 09:40 UTC, Willem-Dekker requested changes

2021-07-12 09:40 UTC, Willem-Dekker commented on docs/apv.md
> +1. Het campen van een niet actieve pluk op Narcopolis is niet toegestaan. Onder campen wordt verstaan het langer dan 15 minuten aanwezig zijn van een persoon of voertuig op een drugs locatie.
pluk vervangen voor drugs locatie

2021-07-12 17:05 UTC, Willem-Dekker approved these changes

2021-07-12 17:05 UTC, merged