Aanpassing A7 - Inbeslagname
Tedeapolis/wet-en-regelgeving pull request #166
Opened 2021-08-08 18:55 UTC by TDA-SanderD

- Vanaf heden geldt er geen limiet meer voor het bedrag dat je moet betalen om je voertuig uit de opslag te kopen. Het bedrag blijft nog steeds 20% van de cataloguswaarde.

2021-08-09 07:39 UTC, marvinh85 commented
Is dat niet wat overdreven... 200K was al best veel. Vaak zit er ook nog een veroordeling aan vast waarvoor je moet betalen. En als je auto in beslag wordt genomen vanwege een verkeersdelict staat het bij dure auto's helemaal niet meer in verhouding... Greetz, Christian Merks

2021-08-09 09:10 UTC, marvinh85 commented
Ik, en een aantal andere binnen Justitie zijn hier geen voorstander van. Bij een auto van 3,1Miljoen betaal je dan 620K aan boete om hem terug te krijgen. Dit staat echt niet in verhouding en is dan ook niet meer leuk voor de bewoners. Het is en blijft en spel en moeten voorkomen dat er teveel regels komen die ervoor zorgen dat het niet leuk meer wordt. 200K is al enorm veel in de economie binnen TDA.

2021-08-09 16:36 UTC, Willem-Dekker commented
Is het niet slimmer om een hoger max te doen ipn geen max. Dit gaan namelijk heel demotiverend zijn voor spelers en alleen maar zorgen voor een negative sfeer binnen de server en meer gezeur.

2021-08-09 16:46 UTC, JamesMercer-1 commented
Ik zou dit een heel raar voorstel vinden. In het verleden werd criminelen kwalijk genomen altijd geld te hebben maar niets op te spel te zetten door bijvoorbeeld overvallen op Sanchez te doen. Nu doen ze dat wel en wordt je alsnog gestraft met een extreem hoge boete. Tevens is er voor criminelen ook nog steeds geen mogelijkheid om je voertuig zonder te betalen terug te kunnen krijgen van de politie. Dit balanceert niet het crimineel vs politie verhaal, dit zal mensen alleen maar demotiveren.

2021-08-09 20:30 UTC, TDA-SanderD commented
> Is het niet slimmer om een hoger max te doen ipn geen max. Dit gaan namelijk heel demotiverend zijn voor spelers en alleen maar zorgen voor een negative sfeer binnen de server en meer gezeur.

Dit is besproken tijdens het staff overleg en toen was iedereen het er unaniem mee eens.

2021-08-09 20:30 UTC, TDA-SanderD commented
> Ik zou dit een heel raar voorstel vinden. In het verleden werd criminelen kwalijk genomen altijd geld te hebben maar niets op te spel te zetten door bijvoorbeeld overvallen op Sanchez te doen. Nu doen ze dat wel en wordt je alsnog gestraft met een extreem hoge boete. Tevens is er voor criminelen ook nog steeds geen mogelijkheid om je voertuig zonder te betalen terug te kunnen krijgen van de politie. Dit balanceert niet het crimineel vs politie verhaal, dit zal mensen alleen maar demotiveren.

Mensen gebruiken hypercars om criminele activiteiten te plegen. Met een automatisch wapen uit een lamborghini schieten vinden wij dan ook niet bepaald realistisch. 

Ze komen vrijwel altijd weg. Als ze wel gepakt worden, zijn ze simpelweg wat meer geld kwijt. 

Iedereen van het staff team die aanwezig was, is het ermee eens, ook de “criminele” staffleden.

2021-08-09 20:31 UTC, Willem-Dekker commented
> > Is het niet slimmer om een hoger max te doen ipn geen max. Dit gaan namelijk heel demotiverend zijn voor spelers en alleen maar zorgen voor een negative sfeer binnen de server en meer gezeur.
> 
> Dit is besproken tijdens het staff overleg en toen was iedereen het er unaniem mee eens. 

Deze oplossing komt niet in de server/wetboek.

2021-08-09 20:34 UTC, Willem-Dekker commented
Dit is niet de oplossing voor het probleem. Dit is je het er makkelijk vanaf maken en gewoon voor het minste of geringste geld van anderen afpakken. Dit is ook iets wat met andere takken van de server (justie) moet worden gedaan en niet staff.

2021-08-09 20:35 UTC, Willem-Dekker requested changes
Deze aanpassing heeft is een gigantische middelvinger naar eerlijk behandelen van spelers zeker nu ook alle schade vergoedingen er ook uit moeten...

2021-08-09 21:08 UTC, Willem-Dekker approved these changes
Hogeraad.

2021-08-09 21:08 UTC, merged

2021-08-10 07:02 UTC, marvinh85 commented
Helaas...