Offroad Voertuigen voorbeeld
Tedeapolis/wet-en-regelgeving pull request #176
Opened 2021-09-03 11:02 UTC by timfloors

Voorbeeld voor de pagina met offroad voertuigen zoals aangegeven in mijn agendapunt. bij goedkeuring zal ik hem afmaken

2021-09-08 13:39 UTC, Willem-Dekker requested changes
Zie eerste commentaar van het document.

2021-09-08 13:39 UTC, Willem-Dekker commented on docs/offroadvoertuigen.md
> +| | |
Zet er ff bij wat welke kolom is.

2021-09-08 13:39 UTC, Willem-Dekker commented on docs/offroadvoertuigen.md
> +| Guardian | A |
Wit regel aan het eind van een document

2021-09-13 06:15 UTC, Willem-Dekker requested changes
Linting issues

2021-09-13 06:15 UTC, Willem-Dekker commented on docs/offroadvoertuigen.md
> +Bij het rijden met een voertuig op een pad of weg waarvoor deze niet bedoeld is valt dit onder "Artikel 10 - Deelname aan het verkeer"
geen spatie aan eind van zin

2021-09-13 09:53 UTC, marvinh85 reviewed
Wat opmerkingen/wijzigingen.

2021-09-13 09:53 UTC, marvinh85 commented on docs/offroadvoertuigen.md
> +|V| Verharde Baan    | een verhard weg waarbij het wegdek uit asfalt of beton bestaat |
|V| Verharde weg | een verharde weg waarbij het wegdek uit asfalt of beton bestaat |

2021-09-13 09:53 UTC, marvinh85 commented on docs/offroadvoertuigen.md
> +|O| Onverharde Baan  | een onverhard pad waarbij het wegdek uit zand bestaat |
|O| Onverharde weg | een onverhard pad of weg waarbij de ondergrond uit zand bestaat |

2021-09-13 09:53 UTC, marvinh85 commented on docs/offroadvoertuigen.md
> +|A| Off-Road         | een pad waarbij er geen wegdek is en de ondergrond uit gras, zand of modder bestaat |
|A| Off-Road | De ondergrond waarop wordt gereden bestaat uit gras, zand of modder en er is geen zichtbaar pad of weg aanwezig |

2021-09-13 09:53 UTC, marvinh85 commented on docs/offroadvoertuigen.md
> +De Lijst hieronder geeft aan welke voertuigen vanuit de gemeente zijn toegestaan om te gebruiken buiten de geasfalteerde wegen, we klassifiseren dit onder:
De lijst hieronder geeft aan welke voertuigen vanuit de gemeente zijn toegestaan om te gebruiken buiten de geasfalteerde wegen, we classificeren dit onder:

2021-09-13 09:53 UTC, marvinh85 commented on docs/offroadvoertuigen.md
> +Bij het rijden met een voertuig op een pad of weg waarvoor deze niet bedoeld is valt dit onder "Artikel 10 - Deelname aan het verkeer"
Bij het rijden met een voertuig op een pad of weg, waarvoor deze niet bedoeld is valt dit onder "Artikel 10 - Deelname aan het verkeer" van de APV

2021-09-14 07:35 UTC, timfloors reviewed
Als et goed is hoort zo alles te kloppen

2021-09-15 08:38 UTC, Willem-Dekker approved these changes

2021-09-15 08:38 UTC, merged