Verzwaring Artikelen 11 & 25 + Verduidelijking/Toevoeging
Tedeapolis/wet-en-regelgeving pull request #230
Opened 2021-12-13 14:46 UTC by timfloors

Verzwaring Artikel 11 NVOL - cat 1 naar cat 2
Verzwaring Artikel 25 RDM - cat 1 naar cat 2
Toevoeging verwijdering wapen na meerdere keren RDM

2021-12-15 12:30 UTC, Willem-Dekker requested changes

2021-12-15 12:30 UTC, Willem-Dekker commented on docs/apv.md
> +3. De overtreding zoals beschreven in lid 1 staat bekend als “no value of life”.
Wat is er met nummer 2 gebeurt?

2021-12-15 12:30 UTC, Willem-Dekker commented on docs/apv.md
> +4. Enkele voorbeelden hiervoor zijn:
waar voor? waar voor zijn dit voorbeelden?

2021-12-15 12:30 UTC, Willem-Dekker commented on docs/apv.md
> +2. Mocht dit artikel meerdere keren zijn overtreden zal het gebruikte wapen ook verwijderd worden.
Hoe vaak? en wat als ik een ander wapen gebruik elke keer?

2021-12-15 12:30 UTC, Willem-Dekker commented on docs/apv.md
> +3. Deze straf kan meerdere malen gegeven worden indien er meer dan één persoon van het leven beroofd is.
wat bedoel je hier mee? dus per persoon 1x een cat 2 ban?

2021-12-16 08:32 UTC, timfloors commented on docs/apv.md
> +3. De overtreding zoals beschreven in lid 1 staat bekend als “no value of life”.
fixed

2021-12-16 08:32 UTC, timfloors commented on docs/apv.md
> +2. Mocht dit artikel meerdere keren zijn overtreden zal het gebruikte wapen ook verwijderd worden.
fixed

2021-12-16 08:33 UTC, timfloors commented on docs/apv.md
> +4. Enkele voorbeelden hiervoor zijn:
fixed

2021-12-16 08:33 UTC, timfloors commented on docs/apv.md
> +3. Deze straf kan meerdere malen gegeven worden indien er meer dan één persoon van het leven beroofd is.
fixed

2021-12-17 22:38 UTC, Willem-Dekker requested changes

2021-12-17 22:38 UTC, Willem-Dekker commented on docs/apv.md
> +2. Mocht dit artikel 2 maal of vaker overtreden zijn dan zal het gebruikte wapen, voor de overtreding, ook verwijderd worden.
Is dit personen of overtredingen? Kan nu dubbel zijn namelijk

2021-12-21 07:19 UTC, Willem-Dekker commented on docs/apv.md
> +2. Mocht dit artikel 2 maal of vaker overtreden zijn dan zal het gebruikte wapen bij de overtreding ook verwijderd worden.
Wat gebeurt er als ik 2 keer in 6 maand dit doe ben ik het dan ook kwijt?

2021-12-27 18:29 UTC, timfloors commented
n.a.v. staffoverleg goedgekeurd (ready to merge)

2022-01-02 18:37 UTC, Willem-Dekker commented on docs/apv.md
> +2. Mocht dit artikel 2 maal of vaker overtreden zijn dan zal het gebruikte wapen bij de overtreding ook verwijderd worden.
?

2022-01-10 08:57 UTC, Willem-Dekker approved these changes

2022-01-10 08:57 UTC, merged