Aanpassing artikel 27 n.a.v. staffoverleg 20-12
Tedeapolis/wet-en-regelgeving pull request #232
Opened 2021-12-20 19:13 UTC by RonaldDaquila

2021-12-21 07:20 UTC, Willem-Dekker requested changes

2021-12-21 07:20 UTC, Willem-Dekker commented on docs/apv.md
> +    * Het dragen van een vuurwapen, steek- of slagwapen
vuur-, steek- of slagwapen

2022-01-16 20:54 UTC, Willem-Dekker commented
Graag gevraagde aanpassingen doen

2022-01-17 17:41 UTC, RonaldDaquila commented on docs/apv.md
> +    * Het dragen van een vuurwapen, steek- of slagwapen
Yes dat bedoel ik :)

2022-01-23 19:49 UTC, closed without merging