Toevoeging/Verduidelijking Verbod ERP
Tedeapolis/wet-en-regelgeving pull request #246
Opened 2022-01-16 19:39 UTC by timfloors

2022-01-16 19:40 UTC, timfloors commented
Besproken binnen staffoverleg - dit is de gevraagde PR

2022-01-16 20:29 UTC, timfloors commented
![afbeelding](https://user-images.githubusercontent.com/56398140/149676893-02114256-5fd9-4daa-a9f4-2d23a1a8c93e.png)
Goedgekeurd, Ready to Merge

2022-01-16 20:57 UTC, Willem-Dekker requested changes

2022-01-16 20:57 UTC, Willem-Dekker commented on docs/apv.md
> +    * Enkel dansen als stripper in de stripclub.
spatie aan het eind weg halen

2022-01-17 07:12 UTC, Willem-Dekker approved these changes

2022-01-17 07:12 UTC, merged