Toevoeging Artikel VIII-14 en Artikel VIII-15
Tedeapolis/wet-en-regelgeving pull request #255
Opened 2022-01-20 20:53 UTC by LM-666

Met de uitbreiding van de KvK in TeDeapolis heb ik in overleg met korpsleiding (Florian en Sander) 2 artikels toegevoegd met betrekking tot de kvk.

2022-01-22 11:51 UTC, Willem-Dekker commented
wij als server weten hier niks van .... is dit overlegd met hogeraad?

2022-01-22 18:55 UTC, LM-666 commented
niet dat ik weet @Willem-Dekker . Heb het er wel met timathy en KL over gehad, was niet op de hoogte dat hogeraad hier ook bij betrokken moet worden.

2022-01-23 19:55 UTC, Willem-Dekker requested changes

2022-01-23 19:55 UTC, Willem-Dekker commented on docs/wetboek.md
> +2. Indien een opsporingsambtenaar merkt dat de schuldige nergens van afwist, dan kan deze zijn discretionaire bevoegdheid gebruiken om het af te doen met een waarschuwing in de    vorm van een notiti
Haal de extra spaties weg pls

2022-01-23 19:55 UTC, Willem-Dekker commented on docs/wetboek.md
> +3. Indien een opsporingsambtenaar merkt dat de schuldige nergens van afwist, dan kan deze zijn discretionaire bevoegdheid gebruiken om het af te doen met een waarschuwing in de    vorm van een notiti
Haal de extra spaties weg pls

2022-01-23 19:55 UTC, Willem-Dekker commented on docs/wetboek.md
> +3. Indien een opsporingsambtenaar merkt dat de schuldige nergens van afwist, dan kan deze zijn discretionaire bevoegdheid gebruiken om het af te doen met een waarschuwing in de    vorm van een notiti
Haal de extra spaties weg pls

2022-01-23 19:55 UTC, Willem-Dekker commented
bij aanspassingen kan deze er in. is besproken in staffoverleg

2022-02-07 19:14 UTC, Willem-Dekker approved these changes

2022-02-07 19:16 UTC, merged