Terroristisch misdrijf (134a 142a SR)
Tedeapolis/wet-en-regelgeving pull request #320
Opened 2022-05-10 11:54 UTC by marvinh85

Toevoeging van Terroristisch misdrijf aan TDA Wetboek.

2022-05-10 12:02 UTC, marvinh85 commented
Loopt een thread binnen #suggesties-voor-wetsartikelen waar hOvJ's en KL en Justitie op kan reageren of met voorstellen/aanpassingen kan komen. Artikel is dus nog niet definitief, maar ter discussie

2022-05-16 15:29 UTC, marvinh85 commented
Na KL overleg is besloten dat dit artikel toegevoegd mag worden aan het wetboek na kleine aanpassing. Lid 5 en 6 toegevoegd.
In afwachting van Sander/KL ter definitief akkoord @TDA-SanderD

2022-05-17 16:24 UTC, TDA-SanderD commented
Akkoord

2022-05-21 14:44 UTC, Willem-Dekker requested changes

2022-05-21 14:44 UTC, Willem-Dekker commented on docs/wetboek.md
> +|   | *Celstraf*  | *Taakstraf*  | *boete*  |
Toevoegen aan kosten pagina

2022-05-29 18:25 UTC, Willem-Dekker approved these changes

2022-05-29 18:25 UTC, merged