Toevoeging Artikel VIII-17
Tedeapolis/wet-en-regelgeving pull request #326
Opened 2022-05-25 11:42 UTC by Mikajac

Toevoeging van Artikel VIII-17 Misdrijven tegen de openbare orde (131 SR) na overleg met en goedkeuring van Timathy en Sander.

2022-05-25 16:34 UTC, marvinh85 commented
Dit overlapt met https://github.com/Tedeapolis/wet-en-regelgeving/pull/320 ....

2022-05-26 18:34 UTC, Mikajac commented
> Dit overlapt met #320 .... Alleen lid 1 zou dan blijven staan

Enig idee hoe ik lid 2 eruit kan verwijderen of moet ik dan een compleet nieuw verzoek aanmaken?

2022-05-27 10:52 UTC, marvinh85 commented
@Willem-Dekker , kan jij @Mikajac hiermee helpen :)

2022-05-29 18:26 UTC, Willem-Dekker commented
je zou nu de aanpassingen kunnen maken

2022-05-30 14:43 UTC, Mikajac commented
Aanpassing is doorgevoerd, lid 2 is verwijderd.

2022-05-30 16:16 UTC, Willem-Dekker requested changes

2022-05-30 16:16 UTC, Willem-Dekker commented on docs/wetboek.md
> +|  Eerste Veroordeling |  | 20 uur | € 2500,-  |
Toevoegen aan kosten pagina?

2022-05-30 16:37 UTC, Mikajac commented on docs/wetboek.md
> +|  Eerste Veroordeling |  | 20 uur | € 2500,-  |
> Toevoegen aan kosten pagina?

Is toegevoegd, zie #329

2022-06-05 18:06 UTC, Willem-Dekker approved these changes

2022-06-05 18:07 UTC, merged