Aanpassing WOK-statussen en boetes
Tedeapolis/wet-en-regelgeving pull request #341
Opened 2022-07-11 19:50 UTC by TDA-SanderD

2022-07-12 14:35 UTC, marvinh85 commented
@TDA-SanderD Tabel opmaak gaat niet helemaal goed

![image](https://user-images.githubusercontent.com/77625852/178515855-4f040dc4-55b6-4f2a-b664-5a5159eeb33a.png)

2022-07-18 11:40 UTC, Willem-Dekker requested changes

2022-07-18 11:40 UTC, Willem-Dekker commented on docs/wetboek.md
> +|  | *Taakstraf*  | *Sanctie*
| aan het einde van deze regel maken

2022-08-16 18:33 UTC, Willem-Dekker approved these changes

2022-08-16 18:34 UTC, merged