Toevoeging A12 - Voorhechtenis
Tedeapolis/wet-en-regelgeving pull request #372
Opened 2022-11-07 08:19 UTC by LM-666

NAV een suggestie dit genoteerd in het wetboek, dan is het voor iedereen duidelijk. Dit is deels besproken met @TDA-SanderD , kan doorgevoerd worden na overleg met de rest van Korpsleiding.

2022-11-21 20:03 UTC, musician1011 requested changes

2022-11-21 20:03 UTC, musician1011 commented on docs/wetboek.md
> +    2. Voorhechtenis kan alleen gegeven worden indien er overtuigend bewijs is dat de
Als deze nog aangevuld wordt, lijkt het voor mij in orde.

2022-12-05 10:11 UTC, Luci-fer12 commented
@TDA-SanderD kan deze al door gevoerd worden? of moest dit nog overlegd worden met KL?

2022-12-05 10:18 UTC, musician1011 approved these changes

2022-12-05 10:18 UTC, musician1011 approved these changes

2022-12-05 10:18 UTC, musician1011 commented on docs/wetboek.md
> +    2. Voorhechtenis kan alleen gegeven worden indien er overtuigend bewijs is dat de
In orde!

2022-12-05 13:19 UTC, merged