Toevoeging van Artikel 5a WvW
Tedeapolis/wet-en-regelgeving pull request #52
Opened 2021-01-07 16:25 UTC by TDA-SanderD

- Er is een artikel toegevoegd waarin het strafbaar is gesteld om opzettelijk ernstig gevaar of hinder te veroorzaken op de openbare weg. Dit artikel kan gerekend worden tot de ernstige strafbare feiten. Het is dan ook een misdrijf. Er mag enkel veroordeeld worden voor dit artikel na toestemming van een (h)OvJ of rechter.

2021-01-07 18:33 UTC, Willem-Dekker requested changes
Graag even kijken naar het commentaar

2021-01-07 18:33 UTC, Willem-Dekker commented on docs/wetboek.md
> +|   | *Celstraf*  | *Taakstraf*  | *boete*  | *rijontzegging* |
Deze boetes ook op de kosten pagina

2021-01-07 18:33 UTC, Willem-Dekker commented on docs/wetboek.md
> +4. Hierbij gelden de volgende aandachtspunten:
Nummering klopt niet

2021-01-07 18:33 UTC, Willem-Dekker commented on docs/wetboek.md
> +5. Veroordeling voor dit artikel kan enkel verlopen met toestemming van een (h)OvJ of een rechter.
Nummering klopt niet + geen spatie aan het eind van de regel

2021-01-07 18:33 UTC, Willem-Dekker commented on docs/wetboek.md
> +6. Op basis van inschatting van de feiten en omstandigheden kan eveneens overgegaan worden tot invordering van het rijbewijs.
Nummering klopt niet

2021-01-07 18:33 UTC, Willem-Dekker commented on docs/wetboek.md
> +a. onvoldoende rechts houden op onoverzichtelijke plaatsen;
Deze vorm val lijsten werkt niet

2021-01-07 18:33 UTC, Willem-Dekker commented on docs/wetboek.md
> +a. Het moet gaan om een opzettelijke gedraging, waardoor de verkeersregels ernstig worden geschonden. Dus gaat het om een onverantwoordelijk en roekeloos rijgedrag, ook wanneer daardoor (nét) geen on
Deze vorm van lijsten werkt niet

2021-01-08 15:11 UTC, TDA-SanderD commented
Alle issues gecorrigeerd, boetebedragen toegevoegd aan de kostenpagina en nog wat kleine wijzigingen/formuleerverbeteringen toegevoegd.

2021-01-18 18:03 UTC, Willem-Dekker approved these changes

2021-01-18 18:08 UTC, merged